### ISSUE TITLE
为什么embedding的长度要设置为1536呢？

### ISSUE THREAD

**Issue by heyday111** [LC1332/Luotuo-Text-Embedding#2]
设置成1536在一些计算密集型的工程上耗时过长，如果最后一层线性层是压缩而不是扩大embedding长度，对结果会有什么影响呢？

**Comment by BlairLeng** [comment]
1536能表达的信息更大，btw你有联系方式吗，可以加我微信cubylza，冷子昂

**Comment by LC1332** [comment]
@heyday111 你可以看我在report中的描述 1536是为了完全对齐openAI的特征，可以实现平替。 我在discussion里面也说了 如果工业上想很快，可以再压缩训练一个binary的短码。
