### ISSUE TITLE
分享句向量相关测试

### ISSUE THREAD

**Issue by DunZhang** [LC1332/Luotuo-Text-Embedding#6]
你们好，非常感谢你们的开源，从roformer-sim开源后，就几乎没有再见到向量开源了(rocket qa除外)。
下面是我自己的一些测试经验：
1，ada-embedding002在中文长短文本匹配上效果是好的，但是在短短匹配上比不上simbert
2，直接蒸馏句向量是比较难学的
3，你们的构造训练数据的方法，相邻句子相似，我觉得这个监督性还是太小了
4，在非蒸馏学习的loss，你们bsz是多少，我这边实测发现最好能达到万级别以上
5，我在已有的数据和我司自己的数据上做了测试，效果还是不尽如人意，不知道是不是使用场景的问题：

<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

  | roformer-sim | luotuo
-- | -- | --
FAQ平均值 | 0.919 | 0.893
  |   |  
Fact检索@5 | 0.878 | 0.821
  |   |  
adat_dev | 0.720799072 | 0.452735217
atec_dev | 0.401090088 | 0.169511474
bq_dev | 0.536377034 | 0.432546669
chip_dev | 0.578700793 | 0.399824329
covid_dev | 0.733037115 | 0.385359669
lcqmc_dev | 0.664989281 | 0.318639524
sts-b_dev | 0.782783621 | 0.614373027
xunfei_dev | 0.753466376 | 0.427438025
oppo_dev | 0.43162646 | 0.248238768
qbqtc_test | 0.260952008 | 0.219000274
sohu_dev | 0.491573167 | 0.418864127
mnli_dev | 0.262145073 | 0.216817413
ocnli_dev | 0.127214601 | 0.122643438
snli_test | 0.340461032 | 0.304840797

</body>

</html>

最后想问下又没交流群可供交流

**Comment by BlairLeng** [comment]
首先非常感谢Zhang老师的测试，看到了分数不低我们也比较高兴！

短短上我们没有很好，我觉得和数据集有一定的关系，因为我们是用CnewSum数据集来做的，所以都是长文本，短短文本的这个数据集我们也想近期做一个试一下。

相邻句子相似的假设是建立在新闻数据集中前后语句相关这个假设之上的。

我们当时训练的batch size不是很大，大概是不到千的级别，主要当时受限于机器，我们因为是开源的社区，机器一直是一个很大的问题，如果您这边有好的计算资源我们也很希望可以合作。

关于在贵司场景的测试中没有取得足够好的效果，我认为和训练数据的新闻domain属性太强有关系，如果您这边可以share一些思考或数据，我们可以合作来做的更好。

我们有赞助我们的赞助者群，一起贡献的贡献者群，如果您感兴趣，可以加我微信: cubylza。

再次感谢您的关注！

**Comment by BlairLeng** [comment]
@DunZhang

**Comment by LC1332** [comment]
大佬您加一下冷子昂微信吧我们之后讨论。 因为现在初步只使用了新闻数据去训练，意外的居然能在其他domain使用，已经很惊讶了。 我们希望之后能够去补充wiki和学术的数据。 另外我们观测到了在QA，和短-长 这些场景下这个embedding有缺陷，甚至弱于openAI，这个应该通过加数据可以增强一些。我们可以讨论一下看看。
